[theme]
primaryColor="#da9421"  # Bright gold, stands out and grabs attention
backgroundColor= "#477175"  # Muted teal adding sophistication
secondaryBackgroundColor="#96401f"  # Rich, burnt orange for secondary elements
textColor="#d5d6b4"  # Light beige, soft and calming for text
font="sans serif"  # Maintains the theme's modern and sophisticated vibe